name:                haskell-project
version:             0.1.0.0
github:              "githubuser/haskell-project"
license:             BSD3
author:              "Avinash Babu, Yash Raj Kumar Lahoti, Aaditya Chintaman Punekar, Khyati Sharadbhai Patel"
maintainer:          "a.babu@se21.qmul.ac.uk, y.lahoti@se21.qmul.ac.uk, a.punekar@se21.qmul.ac.uk, k.patel@se21.qmul.ac.uk"
copyright:           "2021 Avinash Babu, Yash Raj Kumar Lahoti, Aaditya Chintaman Punekar, Khyati Sharadbhai Patel"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-project#readme>

dependencies:
- base >= 4.7 && < 5
- sqlite-simple
- http-conduit
- aeson
- bytestring
- unicode-show
- with-utf8
- time

library:
  source-dirs: src

executables:
  haskell-project-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-project

tests:
  haskell-project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-project
